### ISSUE TITLE
GPIB interface

### ISSUE THREAD

**Issue by kristinadvorska97** [TIS2020-FMFI/plazma#10]

**Comment by Xengaroo** [comment]
1. Treba podrobne opísať čo je to GPIB, ako funguje, prečo práve tento používa náš prístroj.
2. Načo ku komunikácii potrebujeme Agilent/Keysight/National instruments kartu a čo ona vlastne robí.
3. Možno spomenúť a opísať niektoré príkazy tejto karty - také čo asi budeme potrebovať.

**Comment by pavelpetrovic** [comment]
skuste pripadne niekto otestovat toto
https://stackoverflow.com/questions/42850597/python-run-external-program-with-input-and-output-stream

**Comment by pavelpetrovic** [comment]
a tento?
https://www.cyberciti.biz/faq/python-run-external-command-and-get-output/

**Comment by pavelpetrovic** [comment]
Dokončil som pre Vás prvú verziu tej konzolovej aplikácie, ktorú môžete použiť na komunikáciu s prístrojom.

https://github.com/TIS2020-FMFI/plazma/tree/Resources/Prilohy/GPIB-%20zdrojove%20kody/hpctrl

Mohli by ste to prípadne niekto skúsiť, či Vám to ide skompilovať. 

Je tam aj príklad na to, ako sa to dá použiť z pythonu, pričom to v pozadí beží a pythonový program si s tým v pozadí rozpráva a vymieňa údaje.

https://github.com/TIS2020-FMFI/plazma/blob/Resources/Prilohy/GPIB-%20zdrojove%20kody/hpctrl/hp.py

Dá sa teda pripojiť/odpojiť, vytiahnuť meranie, vytiahnuť stav a kalibrácia(aj so stavom) a funguje aj priamy "terminálový" režim posielania príkazov a získavania odpovedí. 

Pripájam príklad jednej malej session 
[example_session.txt](https://github.com/TIS2020-FMFI/plazma/files/5506938/example_session.txt)
(iba malá ukážka čítania, ale ide aj posielanie stavu/kalibrácie).

Priebežne to budem ešte upravovať podľa potreby.

A môžeme čoskoro skúsiť prepnúť čítanie z režimu 4 do režimu 1, to by malo byť výrazne rýchlejšie (v tom režime sa číta kalibrácia, ale dáta sa čítajú v tom pomalom režime 4).

**Comment by kristinadvorska97** [comment]
Ja som to skúšala, testovala -  mne sa to skompilovať nepodarilo, vyhadzuje chyby.
A možno som robila niečo zle. 

Ak sa to niekomu podarí, nech sa mi ozve. :)

Ešte sa tomu povenujem a ak sa mi to nepodarí spojazdniť sa Vám ozvem @pavelpetrovic

**Comment by pavelpetrovic** [comment]
najneskor v piatok na stretnuti sa pozrime co Vam to vypisuje

**Comment by pavelpetrovic** [comment]
ahojte, aktualizoval som ten nas hpctrl:

* opravil som to, ze neslo nastavit stav a kalibraciu, lebo sa bil vstup s pastenutymi hodnotami, zda ze uz je to ok
* pridal som moznost nastavit format komplexnych cisel prikazom FMT RI, FMT MA, FMT DB: z pristroja sa vzdy cita RI, ale do vystupu sa uz vypisuje podla prave nastaveneho formatu
* pridal som moznost zmenit jednotku frekvencie (FREQ HZ, FREQ KHZ, FREQ MHZ, FREQ GHZ) - ovplyvnuje to tak isto ako pri vna.exe len prvy stlpec vo vypise, na pristroji sa tym nic neprepina
* upravil som vystup, aby sa co najviac podobal na ten, co produkuje vna.exe (aj z tym info o formate a freq na zaciatku)
* doplnil som moznost tahat z pristroja data v uspornom internom binarnom formate (prepina sa to prikazom FORM1, FORM4, defaultne je ten usporny FORM1), bola to trochu detektivka, kedze v manuale o tom nie je vsetko podstatne info, ale zda sa, ze je to ok. v rychlom rezime taha najrychlejsi kanal v plynulom rezime radovo kazdych 1.2 sekundy

tymto by to malo byt z mojej strany pre Vas pripravene, ak bude treba cokolvek doplnit, vylepsit, dajte vediet.

**Comment by pavelpetrovic** [comment]
reagujem na otázočky, ktoré som dostal:

* testovacie scenare - fajn fajn, idealne vzdy krok-vysledok, krok-vysledok, ale format nepredpisujem, urobte tak, ako je Vam najlahsie, ale aby to splnalo ten ucel, ze sa podla dokumentu da prebehnut vsetko, co je v katalogu
* adresa pristroja sa dá nastaviť parametrom -a 16 pri startovani programu. program sa da ukoncit (tusim exit) a znovu spustit s inou adresou. ale mozeme tam pridat aj zmenu adresy, ked chcete, ktora bude fungovat iba pri odpojenom stave, napriklad ten "connect 16" moze byt tiez. ostane tam aj connect bez cisla a vtedy sa pouzije adresa z prepinaca programu.
* suhlasim, ze staci connect/disconnect

**Comment by pavelpetrovic** [comment]
vystupy z merani
[merania.zip](https://github.com/TIS2020-FMFI/plazma/files/5623712/merania.zip)

**Comment by pavelpetrovic** [comment]
Len poslušne hlásim, že sme otestovali, že the hpctrl funguje rovnako aj na tej PCI karte National Instruments rovnakoako na tom externom USB zariadeni.

**Comment by pavelpetrovic** [comment]
data z testovania piatok 29.1.2021
[piatoook 2021-01-29 18-05-24.644231.zip](https://github.com/TIS2020-FMFI/plazma/files/5895422/piatoook.2021-01-29.18-05-24.644231.zip)
