### ISSUE TITLE
Návrh

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#14]
Celý dokument Návrhu je na tejto linke: https://docs.google.com/document/d/1AjQFbKWA__3lhklHnmVQ7wSqQ9TPufOAs9H6z23w5Bc/edit#

**Comment by kristinadvorska97** [comment]
Začala som z návrhu časti písať **kapitoly 1, 2**
následne sa doplinili na tímovom stretnutí

Spravila som **kapitolu 3 - používateľské rozhranie**

**Comment by Xengaroo** [comment]
Napísal som kapitoly 1.1 a 1.2. 
Zmenil popis súborov kalibrácie a stavu. (2.1.1 a 2.1.2)
Doplnil som podkapitolu do 2.2 a asi to treba inak štruktúrovať.

**Comment by kristinadvorska97** [comment]
Doplnila som zopár definícií príkazov ku 2.2
Štruktúru môžeme potom prerobiť kľudne :)

**Comment by Xengaroo** [comment]
Snažil som sa opísať celú funkcionalitu nášho programu do .txt. Si myslím, že by nám toto mohlo pomôcť, aby sme všetci chápali funkcionalitu rovnako a tiež môže dosť pomôcť pri písaní testovacích scenárov. Ak je niečo nejasné alebo treba niečo doplniť/zmeniť tak píšte. 
[funkcionalita.txt](https://github.com/TIS2020-FMFI/plazma/files/5606411/funkcionalita.txt)

**Comment by kristinadvorska97** [comment]
Do návrhu som pridala aktuálne používateľské rozhranie.
