### ISSUE TITLE
UML - Sekvenčný diagram

### ISSUE THREAD

**Issue by bforgacova** [TIS2020-FMFI/plazma#17]
Študujem dokumentácie k prístroju a spisujem si poznámky ku kalibrácii aby som podľa toho vedela spraviť diagram.

**Comment by bforgacova** [comment]
Spravila som prvé návrhy  - sekvenčný diagram kalibrácie a sekvenčný diagram merania, vložila som to dokumentu návrhu.

**Comment by Xengaroo** [comment]
Boli vytvorené oba sekvenčné diagramy a sú v dokumente Návrh.
