### ISSUE TITLE
Poslať použ. rozhranie zadávateľovi

### ISSUE THREAD

**Issue by kristinadvorska97** [TIS2020-FMFI/plazma#18]
Po schválení katalógu požiadaviek pošlem zadávateľovi navrhnuté používateľské rozhranie.

**Comment by kristinadvorska97** [comment]
Spolu s katalógom požiadaviek odišiel mailom aj návrh používateľského rozhrania.

**Comment by pavelpetrovic** [comment]
nezabudnite, že používateľské rozhranie chcete so zadávateľom aspoň raz prediskutovať aj naživo, nielen mailom.

**Comment by kristinadvorska97** [comment]
Áno to je v procese dohadovania :) 
@pavelpetrovic
