### ISSUE TITLE
Zmeny v katalógu požiadaviek

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#22]
Katalóg už máme schválený, no ak ešte bude treba v ňom robiť nejaké zmeny tak to píšte sem a nakonci ho upravíme. Zmeny v online dokumente zatiaľ nerobte.

**Comment by Xengaroo** [comment]
Zmeny:
do (A) pridať Address,
do B1 a B2 zmeniť na iba kalibráciu,
B4 zmenené na checkbox,
do (D) pridať Points,
do (D) pridať autosave checkbox,
D5 zmeniť,
do 3.3.2 pridať, že grafy sa budú dať zvačšovať - zostáva ešte otvorené ako

**Comment by kristinadvorska97** [comment]
- do **B3** zapracovať dĺžku _PORT1_ a _PORT2_
- do časti **(D) sweep** pridať _checkboxy na výber parametrov_
