### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#24]
Linka na dokument testovacie scenare: https://docs.google.com/document/d/12mn9B4irHA4f7Ikv-Lm_eDR0Q8PQkkkGft1TLeXWoTQ/edit?usp=sharing

**Comment by pavelpetrovic** [comment]
vdaka, zatial sa v tom neorientujem, nejak sa to tam opakuje dvakrat nieco. ale v principe idete na to dobre, nemusi tam byt vela textu, staci co najstrucnejsie napisat tak, aby sa to podla toho ale dalo urobit.
