### ISSUE TITLE
Naprogramovať Adapter

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#26]
Adapter.py - teda celú komunikáciu s hpctrl a prístrojom

**Comment by Xengaroo** [comment]
Ešte pred týždňom:

- vytvoril som asi všetky metódy, ktoré budú volať iné moduly
- niektoré z nich by už mali byť aj funkčné
- začal som pracovať aj na simulácii prístroja kvôli testovaniu

**Comment by pavelpetrovic** [comment]
skusal som aj ten kill na proces z popen() a zafunguje to, spusteny proces to zrusi, dokonca aj vtedy, ked je to hpctrl, ktore je zaseknute v cakani na odpoved z pristroja, takze by to malo fungovat ok s tym rusenim procesu. good luck

**Comment by Xengaroo** [comment]
Funguje.
