### ISSUE TITLE
Naprogramovať použivateľské rozhranie - GUI

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#28]
Gui bez funkčnosti, iba frontend - teda naprogramovať ako to má vyzerať- buttons, sliders, textboxes,..

**Comment by kristinadvorska97** [comment]
Zmena:

- menšie _kozmetické_ úpravy: zarovnanie, veľkosť textov, zmena názvov premenných na logické

- PRESET: - pridanie vyskakovacieho okna, keď je preset úspešný 
                - volanie funkcie preset z adaptéra z funkcie v GUI - kvôli bodu vyššie

- v dolnej časti hlavného okna vzniklo okno ktoré obsahuje informácie: kalibrácia (uložená, neuložená), typ kalibrácie, stav (uložený, neuložený), stav pripojenia

- pokiaľ nie je načítaný stav alebo calibrácia - nie je možné kliknúť na tlačídlo RECALL STATE, LOAD CALIBRATION

- pridanie prepojenia na save project, keď je zaškrtnutý autosave v časti SWEEP

- súbor data_validate.py - doplnenie, ošetrenie vstupov na všetky vstupy čo zatiaľ sú v GUI

- kalibrácia - validácia + presmerovanie na funkcie v adapteri

**Comment by kristinadvorska97** [comment]
Pridala som:

-celú časť grafov - používateľské rozhranie
