### ISSUE TITLE
Tvorba zapisnice z prveho stretnutia so zadavatelom

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#3]
Kazdy by si mal pozriet nahrate video a napisat zapisnicu resp. ju doplnit.

**Comment by Xengaroo** [comment]
Zapisnica: https://docs.google.com/document/d/1MN2di6wiM3C1Gt-AJ63Yf5turyQ16LWwN07FqcMQ4jo/edit#heading=h.3k566vgs773x

**Comment by bforgacova** [comment]
Podopĺňala som zápisnicu ešte o druhé stretnutie so zadávateľom, nech to máme všetko pokope.
