### ISSUE TITLE
Naprogramovať modul pre merania

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#32]
Všetko čo pracuje s nameranými dátami a meraniami - časť Sweep.

**Comment by pavelpetrovic** [comment]
hpctrl sa prestahovalo z branchu Resources do samostatneho repozitara: https://github.com/TIS2020-FMFI/hpctrl

Najdite si prosim niekde vo svojej strukture adresarov miesto, kde si to interne vybalite cez:

git clone https://github.com/TIS2020-FMFI/hpctrl.git

a dajte do readme poznamku, ze tam sa to ma vybalit.
