### ISSUE TITLE
Terminal a hlavne okno

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#60]
Keď sa otvorí terminálové okno tak do hlavného okna sa nesmie dať klikať - lebo to môže pokaziť veci.

**Comment by Xengaroo** [comment]
https://stackoverflow.com/questions/15363923/disable-the-underlying-window-when-a-popup-is-created-in-python-tkinter

**Comment by bforgacova** [comment]
Pridané obmedzenie aby sa nedalo pracovať s GUI počas pracovania s terminálom.
