### ISSUE TITLE
Terminal more functionality

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#61]
1. do terminalu ak napisem "exit" tak nech sa zatvori terminal
2. terminal: sipka hore nech ignoruje odpovede, a prechadza iba prikazami
    - tip: mozno najlepsie vytvorit 2 polia(odpovede,prikazy)
3. Aby pouzivatel vedel nejako rozlisovat prikazy od odpovedi - npr. zobaciky pred prikazami...

**Comment by Xengaroo** [comment]
Este 4. Ak používateľ napíše "help" do terminálu tak sa pošle help do hpctrl, ten vráti svoj help.
Z tochto helpu chceme vystrhnúť iba tie príkazy ktoré platia pre terminál(CMD príkazy), a tie zobraziť.

**Comment by bforgacova** [comment]
Funkcionalitu som doplnila do terminálu.
