### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#62]
Implementovať autosave.
Idea: po stlačení na Run sa Savne projekt(už implementované), a po každom vykonanom meraní sa do toho projektu ešte Savne to meranie.

Pozrieť si v sweepGUI ako je implementovaný button Run/Stop a ako to celé prebieha.
Vo file_manager vytvoriť funkciu, ktorá do posledného zapametaného self.path Savuje iba posledné meranie.

**Comment by kristinadvorska97** [comment]
Done.
