### ISSUE TITLE
Nenakalibrovany pristroj

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#65]
Ked nie je nakalibrovany pristroj tak vravia spravu ako keby sa disconnectlo - opravit.

**Comment by kristinadvorska97** [comment]
**_tkinter.messagebox.showwarning(title="tvoj_text", message="tvoj_text") 
tkinter.messagebox.showerror(title="tvoj_text", message="tvoj_text")_**

**Comment by Xengaroo** [comment]
Ked je nenakalibrovany tak to vyhodi warning a do pamati si nic neulozi.
