### ISSUE TITLE
Run pri manual mode pristroja

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#66]
Ked je pristroj na manual mode tak po stlaceni na Run sa neprepne do Remote mode - takze treba implementovat nejaky timeout a restartnut hpctrl, lebo aj on sa zasekne.

**Comment by pavelpetrovic** [comment]
mam pocit, ze by to mohlo ist bez restartu hpctrl, lebo v niektorych pripadoch sa to z LOCAL v pohode vratilo (myslim, ze ked sme dali getstate)

**Comment by Xengaroo** [comment]
Zatial ma napadli iba dve riesenia:
1. Ze pred kazdym measure treba zavolat nejaky prikaz ktory ho prepne do Remote.
2. Ze sa po poslati measure bude cakat nejaky timeout, potom sa takyto prikaz posle a zase sa zavola measure.

Si myslim ze najrychlejsi taky prikaz je disconnect+connect a ten ho urcite prepne do Remote.
No aj tak sa mi nejako ani jedno riesenie nepaci.

**Comment by Xengaroo** [comment]
Bola implementovaná detekcia kedy ku tomuto dojde a vypísaná spätná väzba používateľovi.
V ďaľšom issue sa rieši čo ďalej s tým.
https://github.com/TIS2020-FMFI/plazma/issues/84
