### ISSUE TITLE
Zrychlit vykreslovanie grafov

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#67]
1. Ak je na grafe vybraty prazdny param, graf je prazdny(teda to nemeriame) tak nech sa nerefreshuje
2. Grafy by mohol vykreslovat iny thread.

**Comment by Xengaroo** [comment]
1 - nerefreshovanie prázdnych grafov je implementované. 
Skúšali sme použiť thready na vykresľovanie, ale toto tkinter nepovolí.
Skúšali sme použiť thready na prepočitávanie hodnôt a všetko okrem vykreslovania
  - fungovalo to, ale v náhodnom čase to padlo bez vypísania chyby.
  - aj tak to grafy zrýchlilo maximálne o pár milisekund, takže vrátili sme sa na staršiu verziu.
Nevieme to už vylepšiť, takže to uzatváram.

**Comment by pavelpetrovic** [comment]
nezabudnite, prosím, upraviť tú šírku okienok, aby pri pohybe myšou nedochádzalo ku prekreslovaniu grafov kvôli tomu, ze sa prepisujú tie hodnoty zobrazené pod grafom, ktoré tam na šírku nevôjdu.

**Comment by kristinadvorska97** [comment]
@pavelpetrovic Áno to už som vyriešila. Malo by to byť v poriadku :)

**Comment by Xengaroo** [comment]
Ešte som sa s tým pohral a podarilo sa mi zrýchliť refreshovanie grafov v niektorých prípadoch.
1. Kvôli tomu ako je threading implementované v pythone tak sa čakalo po každom meraní 0.2s - v tomto čase reagoval na klikanie, no ak by nahodou meranie bolo kratsie ako 0.2s + vykreslenie grafov, tak by sa grafy vždy iba prekreslovali(nebolo by vidno nič na nich).
Teraz gui reaguje vždy keď sa neprekrusľuje graf + graf po prekreslení vždy počká minimálne 0.2s predtým ako čo sa prekreslí na iný - aby človek stihol zachytiť čo na ňom vôbec bolo. Ak sa v tomto čase namerajú dalšie dáta tak sa tieto nezobrazia(ak nie sú posledné) ale zobrazí sa posledné meranie.
Príklad:  prídu mi dáta zo 101 meraní za 1.1s, na grafoch sa mi v poradí zobrazia iba merania 1, 20, 40, 60, 80, 100, 101.
2. Ani prázdne, ani nezmenené grafy sa už dvakrát neprekresľujú. - doteraz sa počas Continous merania prekresľoval aj nezmenený graf keď som bol vždy na jednom tom istom Frame
