### ISSUE TITLE
Katalog poziadaviek

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#7]
Nejaky uvod/nacrt by sme mali mat uz v piatok 9.10.

**Comment by Xengaroo** [comment]
Linka na KP: https://docs.google.com/document/d/1hVKrppiyx0CjgD-9vC-GrojUbWDHR-gXd4V70rVeOaA/edit?usp=sharing

**Comment by pavelpetrovic** [comment]
titulny list ani obsah nepotrebujeme.
podstatny je realny obsah.

**Comment by kristinadvorska97** [comment]
Pripravila som **formát** v tretej kapitole - 3.1 funkčné požiadavky. 
Pridala som nadpisy jednotlivých požiadaviek a taktiež som doplnila: 
**3.1.1 Projekt** - celú pod kapitolu
**3.1.3 Kalibrácia** - tú som naformátovala, pribudla pri stretnutí
**3.1.2 GPIB settings** - časť terminál
**3.1.4** - celú podkapitolu

Tiež som pridala **definíciu formátu Touchstone (SnP)** - nie som si však istá svojim prekladom z angličtiny :D 

Treba vyriešiť aj podkapitolu **2.2 funkcie systému** (to je začaté, nie však kompletné) a treba na komplet doplniť zvyšok **3.1 špecifické požiadavky**
Určite aj po mne skontrolujte, poprípade doplňte.

**Comment by Xengaroo** [comment]
Pridal/zmenil som:
 v 1.4, -  kalibraciu , S-paramtere, touchstone format
1.5. - odkaz na cely projekt, odkaz na touchstone
2.2 - doplnil par riadkov

**Comment by kristinadvorska97** [comment]
Zapracovala som **nejaké** pripomienky z komentárov v katalógu požiadaviek.
A tiež som pridala som **časť F** v kapitole **3.1**, kde som premiestnila niektoré veci ohľadom _grafov_.

Určite to ešte skontrolujte.

**Comment by Xengaroo** [comment]
Kapitola 3:
Doplnil som niektoré časti.
Vybral som nejaké časti z E, ktoré tam nepatrili a hodil ich do F.
Napísal svoje pripomienky ku niektorým častiam a niektoré časti zmenil(vyriešil niektoré komentáre).

**Comment by SamuelnaP** [comment]
Dopisal som informacie ohladom buttonov v kapitole 3

**Comment by Xengaroo** [comment]
Zapracoval som niektoré(nie všetky) pripomienky od cvičiaceho. 
Spísal otázky na zadávateľa o niektorých nejasnostiach, aby sme mohli vyriešiť aj tie ostatné.

**Comment by pavelpetrovic** [comment]
Sľúbil som, že sa ozvem ako to dopadlo s mojim testovaním prístroja.
Narazil som na pár problémov - v softvéri bolo treba niečo ešte ponastavovať a jedna z knižníc, ktoré som skúšal nefungovala, včera sme to ešte spoločne s Dr. Klasom testovali a myslím, že už je to na dobrej ceste, komunikovať to komunikuje. V nasledujúcom sa budem snažiť vyrobiť C-čkový kód a API, ktoré bude s prístrojom komunikovať podľa potreby s tým, že by sme ho obalili pythonovým wrapperom, ak teda idete vyvíjať v Pythone. Na ceste je aj to rozšírenie, ktoré by umožňovalo vytiahnuť z prístroja presne to, čo sa zobrazuje na displeji vo vysokej rýchlosti, toto budeme musieť HW aj SW vyvinúť v spolupráci so zadávateľom, ale Vás by som poprosil, aby ste softvér pripravili tak, aby sa to do neho ľahko integrovalo - to sa teda týka aj katalógu požiadaviek a návrhu. Konkrétne by malo ísť o to, aby softvér dokázal:
* zobrazovať obrázok z displeja, ktorý dostane už ako bitmapu v pamäti (poviete si formát, ktorý Vaša grafická knižnica vie ľahko zobraziť)
* zaznamenávať prichadzajúce dáta do pamäte vo vysokej frekvencii a potom ich následne uložiť do projektu - čiže ako keby tie dáta chodili z toho keysight zariadenia, ale budú chodiť rýchlo za sebou - čiže mal by tam byť priestor pre taký modul, ako sa bude starať o načítavanie dát z keysightu aj pre tento druhý zdroj dát priamo z displeja a aby to zvládlo spracovať a uložiť dáta aj keď ich bude veľa.
V najbližšom období teda treba vyšpecifikovať čo najpresnejšie, ktoré údaje z prístroja prečítať a akými príkazmi.

**Comment by kristinadvorska97** [comment]
- prerobila som **poradie** v kapitole 3.1
- z kapitoly 3.3 som **odstránila bod 3.3.3** - bol pridaný do kapitoly 3.1
- do 3.1 som zapracovala body **F3 a F4**
- pridala som **bod B5** v kapitole 3.1

- pridala som tiež zopár komentárov - ku veciam čo mi nie sú jasné.

**Comment by kristinadvorska97** [comment]
Zapracovali sme **všetky** pripomienky ku katalógu požiadaviek.

Môžete nám ho skontrolovať :) @pavelpetrovic 

_(link na katalóg uvedený vyššie)_

**Comment by pavelpetrovic** [comment]
Dakujem, precital som si novu verziu katalogu poziadaviek.
Vyzera to velmi pekne. Mam jednu prosbu - mohlo by byt pouzivatelske rozhranie v anglictine? (to sa tyka aj vsetkych nazvov suborov a priecinkov, ktore program vytvara) - predsa len hoci to budu vyuzivat predovsetkym fyzici tu, ak to bude fungovat, tak to moze pouzit aj niekto iny a navyse aj tu pracuju rozni cudzinci na stazi a pod... v anglictine tomu bude rozumiet kazdy.
Par drobnosti som este vyznacil priamo v subore na modro a dopisal tam zlty komentar, prosim, zapracujte ich.

**Comment by Xengaroo** [comment]
Katalóg bol poslaný zadávateľovi a vrátil sa s malými pripomienkami.
Tieto pripomienky som zapracoval do nášho google doc-u.
