### ISSUE TITLE
Vytvorit a pripravit discord server

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#8]

**Comment by pavelpetrovic** [comment]
co je discord channel? :)

**Comment by Xengaroo** [comment]
Discord server*. 
Discord je appka, cez ktoru sme sa rozhodli primarne komunikovat(chat, pripadne call).

**Comment by Xengaroo** [comment]
Vytvoreny a ako tak pripraveny, linku na pripojenie som poslal na Messangeri do team chatu.
