### ISSUE TITLE
Zmenit Port1, Port2 zo sekund na picosekundy

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#81]
* 10 ^ - 12.

**Comment by pavelpetrovic** [comment]
*10^(-12) su pico, nie nano. :)

**Comment by Xengaroo** [comment]
Áno, mne sa zdá, že pri testovaní bolo spomínané, že to treba skonvertovať na 10^-12.
No boli spomínané aj nanosekundy, takže nie som si tým istý.
Momentálne sa to konvertuje na 10^-12 , teda pico.

**Comment by pavelpetrovic** [comment]
picosekundy boli posledne spominane.

**Comment by Xengaroo** [comment]
Zmenené na pico.
