### ISSUE TITLE
Prístroj v Remote

### ISSUE THREAD

**Issue by Xengaroo** [TIS2020-FMFI/plazma#84]
Pred meraním nejako vinsť von z Remote modu ak sa podarí.

**Comment by pavelpetrovic** [comment]
teraz som skúšal, že keď je v LOCAL, tak keď sa do hpctrl pošle:
DISCONNECT
CONNECT 16
tak sa zasa prepol do remote režimu. Možno pred meraním by sa to dalo vždy poslať, netrvá to dlho.

**Comment by Xengaroo** [comment]
Mňa zmietlo to, že keď sa pri testovaní toto stalo, tak ste skúšali sa Disconnectnúť a zase Connectnúť a nešlo to.
No už som pochopil prečo, hpctrl bol v tom prípade zamrznutý.

**Comment by Xengaroo** [comment]
Už sa to posiela pred každým meraním.

**Comment by pavelpetrovic** [comment]
Hej hej, ked sa dalo MEASURE vtedy, ked bol pristroj v LOCAL, tak to cele zamrzlo a uz ani disconnect-connect nepomohlo a uz ani EXIT nefungoval.

Ak sa ale MEASURE neposle a posle sa najskor DISCONNECT-CONNECT, tak to nezamrzne a je vsetko fajn.

Aj tak som teraz pre istotu upravil program HPCTRL tak, ze EXIT zafunguje aj vtedy, ked je zamrznuty, takze teraz aj keby sa to stalo z nejakych inych dovodov by uz nemal zamrznut a EXIT by ho mal vzdy vyhodit korektne von.
