### ISSUE TITLE
Poslať katalóg zadávateľovi 

### ISSUE THREAD

**Issue by kristinadvorska97** [TIS2020-FMFI/plazma#9]
Ako náhle budeme mať **kompletný katalóg požiadaviek**, treba ho poslať na schválenie zadávateľovi projektu. :)

**Comment by pavelpetrovic** [comment]
pozor! najskor ho posielate cviciacemu, cize mne. ja Vam ho budem vracat dovtedy, kym s nim nebudem spokojny. az potom ho posielate zadavatelovi na vyjadrenie pre pripadne dalsie upravy a schvalenie.

**Comment by kristinadvorska97** [comment]
@pavelpetrovic áno to berieme do úvahy, preto som dala **kompletny katalóg požiadaviek ** hrubým písmom. Kompletný - tým myslím - schválený vami :)

**Comment by pavelpetrovic** [comment]
super, len ste ma vystrašili, lebo našla sa aj skupina, ktorá to nepochopila.
